Support for services with only query lambda
finos/legend-engine pull request #1040
Opened 2022-10-12 09:39 UTC by gs-gunjan

#### What does this PR do / why is it needed ?
This PR would allow users to create services with just a query written as part of the execution of services.

#### Which issue(s) this PR fixes:

NA

#### Other notes for reviewers:
This is for specifying single execution services with query lambda

#### Does this PR introduce a user-facing change?

No

2022-10-20 04:12 UTC, epsstan requested changes
I like this version better than the previous version where there was a new execution type!

2022-10-20 04:12 UTC, epsstan commented on legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestServiceCompilationFromGrammar.java
> +                "}\n", "COMPILATION error at [26:14-29:3]: function: 'from' needs to be present as part of the lambda, to specify mapping and runtime");
Can we improve this error message ? "from" is not always required right ? 
Can we restate the error message like "Mapping, runtime has not been provided. Either provide via the 'from' function or as separate 'mapping', 'runtime' attributes"

2022-10-20 04:12 UTC, epsstan commented on legend-engine-language-pure-dsl-service/src/test/java/org/finos/legend/engine/language/pure/grammar/test/TestServiceGrammarParser.java
> +                "}\n", "PARSER error at [6:14-10:3]: Field 'runtime' is required");
Same as my comment above. 'runtime' is not required right ? Without 'runtime', this will be a valid inline lambda ?

2022-10-20 04:12 UTC, epsstan commented on legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
> +        //service store service as inline service
You mean .. NOT an inline service ?

2022-10-20 04:12 UTC, epsstan commented on legend-engine-test-runner-service/src/test/java/org/finos/legend/engine/testable/service/TestServiceTestSuite.java
> +        // simply query service
You mean inline service ?

2022-11-15 07:14 UTC, gs-ssh16 approved these changes

2022-11-15 07:18 UTC, closed without merging