WIP
finos/legend-engine pull request #1050
Opened 2022-10-14 07:32 UTC by jinanisha

#### What type of PR is this?

#### What does this PR do / why is it needed ?

#### Which issue(s) this PR fixes:

Fixes #

#### Other notes for reviewers:

#### Does this PR introduce a user-facing change?

2022-10-14 14:05 UTC, epsstan requested changes

2022-10-14 14:05 UTC, epsstan commented on legend-engine-xt-serviceStore-executionPlan/src/main/java/org/finos/legend/engine/plan/execution/stores/service/ServiceExecutor.java
> +                securitySchemes.forEach(securityScheme -> processSecurityScheme(clientBuilder, requestBuilder, profiles, securityScheme,authSpecs.get(securityScheme.id)));
We have to document somewhere that we do (or do not) care about the order of the security schemes

2022-10-14 14:05 UTC, epsstan commented on legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/executionPlan/executionPlan_print.pure
> +   //$space+'  securitySchemes = '+$s.securitySchemes->map(sec | $sec->securitySchemeToString($extensions))->joinStrings('[', ', ' ,']') +'\n'+
remove comment

2022-10-14 14:05 UTC, epsstan commented on legend-engine-xt-serviceStore-pure/src/main/resources/core_servicestore/protocols/pure/vX_X_X/extension/extension_serviceStore.pure
> +      transfers_store_transformConnection2 = { extensions:meta::pure::extension::Extension[*] |
variable name

2022-12-04 12:38 UTC, finos-admin commented
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

2022-12-09 12:39 UTC, finos-admin commented
This PR was closed because it has been inactive for 35 days. Please re-open if this PR is still relevant.

2022-12-09 12:39 UTC, closed without merging