Add parameter values option to execute and executePlan api
finos/legend-engine pull request #1068
Opened 2022-10-19 19:18 UTC by YannanGao-gs

#### What type of PR is this?

#### What does this PR do / why is it needed ?
In Studio, We want to remove the usage of let statements when executing queries with parameters.
The use of let statements makes it difficult for engine to do type matching causing bugs when executing queries with parameters.
As a result we should move over and use engine to execute the queries with parameters.

#### Which issue(s) this PR fixes:

Fixes https://github.com/finos/legend-engine/issues/1018
Links to https://github.com/finos/legend-studio/issues/1535

#### Other notes for reviewers:

#### Does this PR introduce a user-facing change?

2022-10-25 16:16 UTC, MauricioUyaguari requested changes
Looks good. Just small cleanup stuff on naming. 
Also lets add an api test to test execution with executeInput with parameterValues filled out.

2022-10-25 16:16 UTC, MauricioUyaguari commented on legend-engine-query-pure/src/main/java/org/finos/legend/engine/query/pure/api/Execute.java
> +            paraMultiplicity = getFunctionParameterMultiplicity(functionParameters, paraMultiplicity, e);
lets add `parameterValue = parameterToValue.getValue()` before this and use it below to make code more readible

2022-10-27 16:45 UTC, Yasirmod17 requested changes

2022-10-27 16:45 UTC, Yasirmod17 commented on legend-engine-shared-core/src/main/java/org/finos/legend/engine/shared/core/api/model/ParameterValue.java
> +    public ParameterValue(@JsonProperty("name") String name, @JsonProperty("value") ValueSpecification value)
use existing class. Move to proper module if necessary

2022-10-27 16:45 UTC, Yasirmod17 commented on legend-engine-testable/src/main/java/org/finos/legend/engine/testable/helper/PrimitiveValueSpecificationToObjectVisitor.java
> +        return enumValue.value;
Add an enum test to trigger this flow

2022-10-27 16:45 UTC, Yasirmod17 commented on legend-engine-query-pure/src/test/java/org/finos/legend/engine/query/pure/api/test/inMemory/TestServiceExecutionWithParameters.java
> +    private BaseExecutionContext context()
Move to helper and merge with other tests

2022-10-28 20:41 UTC, Yasirmod17 approved these changes

2022-10-31 13:18 UTC, MauricioUyaguari approved these changes

2022-10-31 13:21 UTC, Yasirmod17 approved these changes

2022-10-31 13:21 UTC, merged