Throw warnings for incompatible types in relational property mappings
finos/legend-engine pull request #1205
Opened 2022-11-30 13:12 UTC by saisha95

What type of PR is this?
New feature

What does this PR do / why is it needed ?
It adds compilation check for incompatible type is mapping

Which issue(s) this PR fixes:
Fixes #

Other notes for reviewers:
Does this PR introduce a user-facing change?
yes

2022-11-30 13:16 UTC, vikask-gs commented on legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
> +            //Ignore Exceptions
log the exception

2022-11-30 13:18 UTC, vikask-gs commented on legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
> +                context.pureModel.addWarnings(Lists.mutable.with(new Warning(SourceInformationHelper.fromM3SourceInformation(res.getSourceInformation()), "Types of class property: " + compareRelation
we need to include (Class name.property name) in the error message too, otherwise it will be hard to figure out the wrong property

2022-12-01 06:52 UTC, vikask-gs requested changes

2022-12-01 06:52 UTC, vikask-gs commented on legend-engine-xt-relationalStore-grammar/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRelationalBuilder.java
> +            LOGGER.warn("Ignored exception: ", exception.getMessage());
LOGGER.warn("Ignored exception", exception); is better as it will log the whole trace

2022-12-01 10:54 UTC, vikask-gs approved these changes
Good to merge!

2022-12-02 09:10 UTC, gs-ssh16 approved these changes

2022-12-02 09:10 UTC, merged