Add optional field support for protobuf
finos/legend-engine pull request #1272
Opened 2022-12-27 13:28 UTC by hardikmaheshwari

#### What type of PR is this?
Enhancement

#### What does this PR do / why is it needed ?
Add optional field support for protobuf

#### Which issue(s) this PR fixes:

Fixes #

#### Other notes for reviewers:

#### Does this PR introduce a user-facing change?
Yes, adds a new feature

2022-12-27 14:23 UTC, gs-ssh16 requested changes

2022-12-27 14:23 UTC, gs-ssh16 commented on legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/transformation/fromPure/pureToProtobuf.pure
> +      optional = (!$property.multiplicity->hasLowerBound() || ($property.multiplicity.lowerBound->toOne().value == 0)) && ($property.multiplicity->hasUpperBound() && $property.multiplicity.upperBound
```suggestion
      optional = $property.multiplicity->meta::pure::functions::multiplicity::isZeroOne(),
```

2022-12-27 16:09 UTC, hardikmaheshwari commented on legend-engine-xt-protobuf-pure/src/main/resources/core_external_format_protobuf/transformation/fromPure/pureToProtobuf.pure
> +      optional = (!$property.multiplicity->hasLowerBound() || ($property.multiplicity.lowerBound->toOne().value == 0)) && ($property.multiplicity->hasUpperBound() && $property.multiplicity.upperBound
Thanks Done

2022-12-28 05:47 UTC, gs-ssh16 approved these changes

2022-12-28 05:47 UTC, merged