Add new security schemes/authentication metamodels to service store
finos/legend-engine pull request #1385
Opened 2023-02-10 14:39 UTC by jinanisha

#### What type of PR is this?

Improvement

#### What does this PR do / why is it needed ?

This PR is a part of Legend Authentication refactoring. It introduces structural changes to how we model and use security schemes in service store.

#### Which issue(s) this PR fixes:

#### Other notes for reviewers:

#### Does this PR introduce a user-facing change?
No

2023-02-13 07:33 UTC, hardikmaheshwari requested changes

2023-02-13 07:33 UTC, hardikmaheshwari commented on legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/service/model/SecurityScheme.java
> +import com.fasterxml.jackson.annotation.JsonSubTypes;
Why we need this import?

2023-02-13 07:33 UTC, hardikmaheshwari commented on legend-engine-xt-serviceStore-protocol/src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/AuthenticationSchemeRequirement.java
> +// Copyright 2022 Goldman Sachs
why 2022?

2023-02-13 07:48 UTC, hardikmaheshwari approved these changes
Looks good to me

2023-02-21 08:45 UTC, gs-ssh16 approved these changes

2023-02-21 08:45 UTC, merged