GraphQL - Nested Qualified Properties in Selection Set
finos/legend-engine pull request #1551
Opened 2023-03-20 13:24 UTC by abhishoya-gs

#### What type of PR is this?

#### What does this PR do / why is it needed ?

#### Which issue(s) this PR fixes:

Fixes #

#### Other notes for reviewers:

#### Does this PR introduce a user-facing change?

2023-03-28 14:01 UTC, TheJuanAndOnly99 commented
/easycla

2023-05-08 23:07 UTC, epsstan requested changes

2023-05-08 23:07 UTC, epsstan commented on legend-engine-xt-graphQL-query/src/test/java/org/finos/legend/engine/query/graphQL/api/test/TestGraphQLAPI.java
> +    @Ignore // TODO - Fails as date is not supported as an argument now
Please move this test into a separate PR

2023-05-10 06:27 UTC, abhishoya-gs commented
/easycla

2023-06-14 12:38 UTC, finos-admin commented
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

2023-06-19 12:38 UTC, finos-admin commented
This PR was closed because it has been inactive for 35 days. Please re-open if this PR is still relevant.

2023-06-19 12:38 UTC, closed without merging