open source store entitlements
finos/legend-engine pull request #1678
Opened 2023-04-13 20:16 UTC by YannanGao-gs

#### What type of PR is this?

Improvement
#### What does this PR do / why is it needed ?

#### Which issue(s) this PR fixes:

open source store entitlements

#### Other notes for reviewers:

#### Does this PR introduce a user-facing change?

2023-04-13 20:48 UTC, YannanGao-gs commented
```
model:

###DataSpace
DataSpace domain::COVIDDatapace
{
  executionContexts:
  [
    {
      name: 'dummyContext';
      mapping: mapping::CovidDataMapping;
      defaultRuntime: runtime::H2Runtime;
    }
  ];
  defaultExecutionContext: 'dummyContext';
  title: 'COVID Sample Data';
  description: '# Peleus rupit\n\n## Sum super gerens paterque\n\nLorem markdownum presso, et tamen cogitis, Taenarius lactantia fluxerunt\nterrita, vota. Tempore flumina ferrumque bella.\n\n- Per dixit\n- Truces tellusque indignata ducem\n- Cervice venitis cavernis minus\n\n## Tum ausus fovebam incursus magis dici extemplo\n\nPiscator degenerat desertaque quid scelus tyranni feror ipsa mortis nec silva\nsparsus neci cum? Est patulas meam decorem, dat demit corpora exuritque Ulixes,\ngenitore. Captare certa amore pressos, Diamque\n[traxit](http://istecondar.net/ministropudoris) devorat duritia ecce, capillos\nfuerint progenitore curva relictas. Iubae pectus et quateret, non vires tibi\ncacumina figuram Antigonen rursus verti.\n\n## Dicta nec Thestiadae tristi exempla sed suoque\n\nFlumina quae loricaeque meruique defensae *me terram* tamen attollere totum\nneque nullos. Quem plus, stratum.\n\n## Quaeque si reddite summoque vultu Teleboasque vincere\n\nIsmariae me munus umbram. Usum pedem multis quotiensque mirantum Cephenum et\namori Procne locutum auctor Volturnus pavent virgineas.\n\n    if (edi + sidebarTooltip < aiffDisk) {\n        drive_key_firewire += bank(searchHardBoot(bus, packet_click));\n    }\n    var adRow = dlc_rootkit(rdramMegabit) - hertzBanner * 2 +\n            memory_adc.horizontal(class_box_rte, disk, lte_grep);\n    if (grayscale) {\n        spool_windows_metal.zif_firewire *= 3;\n        emoticon_mp = user.thunderboltIcqBus.installer_remote(4, searchCable) *\n                kibibyteYoutubeRaster.simm(-3, nosqlCharacter, sip);\n    }\n    var blob = -2;\n\n## Est magis interdum in luctus\n\nPrimus illa sub bis infregit saepe agrestem Cyllare lumen cultrosque **Cnosia**.\nSuis est fero durisque satis.\n\n- Nos quas est maesta aliquis se unum\n- Tu ossa Cupido sagitta hanc inflati profuso\n- Modo est proles pavor\n- Stillabant pallada invitaque et tantum dictaque in\n- Generum coegi tum edaci\n\nSuo nec cerae me omnem Famemque, passi si auditque ullo, praebita. Gravi annos\npudore formidabilis erat pectora perpetuo qua oscula cum ad sed Nabataeus\nRomethiumque deum Erectheus? O Victoria rostro utque terras vitisque classe.\nTibi [miserrima hirta](http://decentia-qui.net/docta-petentem), eratis saepius\ntuus.';
  executables:
  [
    {
      title: 'Exec 1';
      description: 'Some exec description';
      executable: service::CovidDataMulti;
    },
    {
      title: 'Exec 2';
      description: 'Some more exec description';
      executable: service::CovidDataSingle;
    }
  ];
}

###DataSpace
DataSpace domain::COVIDDatapaceSnowflake
{
  executionContexts:
  [
    {
      name: 'dummyContext';
      mapping: mapping::CovidDataMapping;
      defaultRuntime: runtime::SnowflakeRuntime;
    }
  ];
  defaultExecutionContext: 'dummyContext';
  title: 'COVID Sample Data';
  description: '# Peleus rupit\n\n## Sum super gerens paterque\n\nLorem markdownum presso, et tamen cogitis, Taenarius lactantia fluxerunt\nterrita, vota. Tempore flumina ferrumque bella.\n\n- Per dixit\n- Truces tellusque indignata ducem\n- Cervice venitis cavernis minus\n\n## Tum ausus fovebam incursus magis dici extemplo\n\nPiscator degenerat desertaque quid scelus tyranni feror ipsa mortis nec silva\nsparsus neci cum? Est patulas meam decorem, dat demit corpora exuritque Ulixes,\ngenitore. Captare certa amore pressos, Diamque\n[traxit](http://istecondar.net/ministropudoris) devorat duritia ecce, capillos\nfuerint progenitore curva relictas. Iubae pectus et quateret, non vires tibi\ncacumina figuram Antigonen rursus verti.\n\n## Dicta nec Thestiadae tristi exempla sed suoque\n\nFlumina quae loricaeque meruique defensae *me terram* tamen attollere totum\nneque nullos. Quem plus, stratum.\n\n## Quaeque si reddite summoque vultu Teleboasque vincere\n\nIsmariae me munus umbram. Usum pedem multis quotiensque mirantum Cephenum et\namori Procne locutum auctor Volturnus pavent virgineas.\n\n    if (edi + sidebarTooltip < aiffDisk) {\n        drive_key_firewire += bank(searchHardBoot(bus, packet_click));\n    }\n    var adRow = dlc_rootkit(rdramMegabit) - hertzBanner * 2 +\n            memory_adc.horizontal(class_box_rte, disk, lte_grep);\n    if (grayscale) {\n        spool_windows_metal.zif_firewire *= 3;\n        emoticon_mp = user.thunderboltIcqBus.installer_remote(4, searchCable) *\n                kibibyteYoutubeRaster.simm(-3, nosqlCharacter, sip);\n    }\n    var blob = -2;\n\n## Est magis interdum in luctus\n\nPrimus illa sub bis infregit saepe agrestem Cyllare lumen cultrosque **Cnosia**.\nSuis est fero durisque satis.\n\n- Nos quas est maesta aliquis se unum\n- Tu ossa Cupido sagitta hanc inflati profuso\n- Modo est proles pavor\n- Stillabant pallada invitaque et tantum dictaque in\n- Generum coegi tum edaci\n\nSuo nec cerae me omnem Famemque, passi si auditque ullo, praebita. Gravi annos\npudore formidabilis erat pectora perpetuo qua oscula cum ad sed Nabataeus\nRomethiumque deum Erectheus? O Victoria rostro utque terras vitisque classe.\nTibi [miserrima hirta](http://decentia-qui.net/docta-petentem), eratis saepius\ntuus.';
  executables:
  [
    {
      title: 'Exec 1';
      description: 'Some exec description';
      executable: service::CovidDataMulti;
    },
    {
      title: 'Exec 2';
      description: 'Some more exec description';
      executable: service::CovidDataSingle;
    }
  ];
}


###Service
Service service::CovidDataMulti
{
  pattern: '/9566f101-2108-408f-863f-6d7e154dc17a';
  owners:
  [
    'anonymous',
    'akphi'
  ];
  documentation: '';
  autoActivateUpdates: true;
  execution: Multi
  {
    query: |domain::COVIDData.all()->project([x|$x.cases], ['Cases']);
    key: 'env';
    executions['PROD']:
    {
      mapping: mapping::CovidDataMapping;
      runtime: runtime::H2Runtime;
    }
    executions['DEV']:
    {
      mapping: mapping::CovidDataMapping;
      runtime: runtime::H2Runtime;
    }
  }
}

Service service::CovidDataMultiSnowflake
{
  pattern: '/9566f101-2108-408f-863f-6d7e154dc17a';
  owners:
  [
    'anonymous',
    'akphi'
  ];
  documentation: '';
  autoActivateUpdates: true;
  execution: Multi
  {
    query: |domain::COVIDData.all()->project([x|$x.cases], ['Cases']);
    key: 'env';
    executions['PROD']:
    {
      mapping: mapping::CovidDataMapping;
      runtime: runtime::SnowflakeRuntime;
    }
    executions['DEV']:
    {
      mapping: mapping::CovidDataMapping;
      runtime: runtime::SnowflakeRuntime;
    }
  }
}

Service service::CovidDataSingle
{
  pattern: '/9566f101-2108-408f-863f-6d7e154dc17b';
  owners:
  [
    'anonymous',
    'akphi'
  ];
  documentation: '';
  autoActivateUpdates: true;
  execution: Single
  {
    query: |domain::COVIDData.all()->project([x|$x.cases], ['Cases']);
    mapping: mapping::CovidDataMapping;
    runtime: runtime::H2Runtime;
  }
}

Service service::CovidDataSingleSnowflake
{
  pattern: '/9566f101-2108-408f-863f-6d7e154dc17b';
  owners:
  [
    'anonymous',
    'akphi'
  ];
  documentation: '';
  autoActivateUpdates: true;
  execution: Single
  {
    query: |domain::COVIDData.all()->project([x|$x.cases], ['Cases']);
    mapping: mapping::CovidDataMapping;
    runtime: runtime::SnowflakeRuntime;
  }
}


###Relational
Database store::CovidDataStore
(
  Table DEMOGRAPHICS
  (
    FIPS VARCHAR(200),
    STATE VARCHAR(200)
  )
  Table COVID_DATA
  (
    ID INTEGER PRIMARY KEY,
    FIPS VARCHAR(200),
    DATE DATE,
    CASE_TYPE VARCHAR(200),
    CASES INTEGER,
    LAST_REPORTED_FLAG BIT
  )

  Join CovidDataDemographicsJoin(DEMOGRAPHICS.FIPS = COVID_DATA.FIPS)
)


###Pure
Enum {doc.doc = 'List of known viruses'} domain::Virus
{
  {doc.doc = 'Severe acute respiratory syndrome (SARS) is a viral respira [...]

2023-04-14 12:42 UTC, akphi approved these changes

2023-04-14 12:42 UTC, akphi commented on legend-engine-extensions-collection-generation/pom.xml
> +            <version>${project.version}</version>
TODO: remove

2023-04-14 12:42 UTC, akphi commented on legend-engine-extensions-collection-generation/pom.xml
> +            <scope>runtime</scope>
why do we need this `runtime` while others don't?

2023-04-14 12:42 UTC, akphi commented on legend-engine-server/pom.xml
> +            <version>${project.version}</version>
TODO: remove `version`

2023-04-14 12:42 UTC, akphi commented on legend-engine-xt-analytics-store-entitlement/src/main/java/org/finos/legend/engine/entitlement/model/specification/DatasetSpecification.java
> +@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "_type", visible = true)
TODO: remove `visible = true`

2023-04-14 12:42 UTC, akphi commented on legend-engine-xt-analytics-store-entitlement-api/src/main/java/org/finos/legend/engine/api/analytics/StoreEntitlementAnalytics.java
> +@Api(tags = "Analytics - Entitlements")
TODO:
```suggestion
@Api(tags = "Analytics - Store Entitlement")
```

2023-04-14 12:42 UTC, akphi commented on legend-engine-xt-analytics-store-entitlement-api/src/main/java/org/finos/legend/engine/api/analytics/StoreEntitlementAnalytics.java
> +            return ManageConstantResult.manageResult(profiles, new SurveyDatasetsResult(datasets), EntitlementModelObjectMapperFactory.getNewObjectMapper());
TODO: create a common private static final `object mapper` instead so we don't need to build it on every API call

2023-04-14 12:42 UTC, akphi commented on legend-engine-xt-data-space-generation/src/main/java/org/finos/legend/engine/generation/analytics/DataSpaceAnalyticsHelper.java
> +    public static ObjectMapper getObjectMapper()
TODO: instead of making all 3 places use this object mapper, create an util `factory` function instead

2023-04-14 12:42 UTC, akphi commented on legend-engine-xt-data-space-generation/pom.xml
> +            <version>${project.version}</version>
TODO: remove version

2023-04-14 12:42 UTC, akphi commented on legend-engine-xt-relationalStore-store-entitlement-analytics/src/test/java/org/finos/legend/engine/entitlement/TestRelationalStoreEntitlementAnalytics.java
> +        testStoreEntitlementAnalyticsRelationalStoreExtension("models/relationalModel.pure", "runtime::H2Runtime", "mapping::CovidDataMapping", "[{\"name\":\"default.DEMOGRAPHICS\",\"type\":\"H2\",\"
TODO: add a test where you have a runtime that has multiple connection and the mapping refers to a store that might use both connection

2023-04-14 12:43 UTC, akphi requested changes

2023-04-14 12:43 UTC, akphi commented on legend-engine-xt-analytics-store-entitlement-api/src/main/java/org/finos/legend/engine/api/analytics/StoreEntitlementAnalytics.java
> +@Path("pure/v1/analytics/entitlements")
```suggestion
@Path("pure/v1/analytics/store-entitlement")
```

2023-04-14 12:43 UTC, akphi approved these changes

2023-04-14 12:50 UTC, merged