fix a bug in service test parameter type validation
finos/legend-engine pull request #1855
Opened 2023-05-26 18:16 UTC by YannanGao-gs

#### What type of PR is this?

Bug fix
#### What does this PR do / why is it needed ?

fix a bug in service test parameter type validation
#### Which issue(s) this PR fixes:

Fixes #

#### Other notes for reviewers:

#### Does this PR introduce a user-facing change?

2023-05-26 18:27 UTC, MauricioUyaguari requested changes

2023-05-26 18:27 UTC, MauricioUyaguari commented on legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java
> +    private static boolean isTypeCompatibleForAssignment(String type, String assignmentType)
this method doesn't seem specific to here. Don't we have another method that would check that an instance value is compatible with a type ?

2023-05-29 04:19 UTC, hardikmaheshwari commented
Lets please add a test case indicating what we are trying to fix. Thanks

2023-05-29 16:05 UTC, MauricioUyaguari commented
> Lets please add a test case indicating what we are trying to fix. Thanks

@YannanGao-gs  please add a compile grammar test for what this change fixes

2023-05-31 22:01 UTC, merged

2023-06-01 03:50 UTC, hardikmaheshwari commented on legend-engine-language-pure-dsl-service/src/main/java/org/finos/legend/engine/language/pure/dsl/service/compiler/toPureGraph/HelperServiceBuilder.java
> +               if (!"Nil".equals(paramValue._genericType()._rawType()))
Yes it is needed actually, I can explain offline if needed