Add schema type and tdsResultColumns to openAPI generation
finos/legend-engine pull request #2135
Opened 2023-08-11 16:55 UTC by janeenyamak1

#### What type of PR is this?

#### What does this PR do / why is it needed ?

#### Which issue(s) this PR fixes:

Fixes #

#### Other notes for reviewers:

#### Does this PR introduce a user-facing change?

2023-08-19 11:50 UTC, hardikmaheshwari requested changes

2023-08-19 11:50 UTC, hardikmaheshwari commented on legend-engine-xts-openapi/legend-engine-xt-openapi-pure/src/main/resources/core_external_format_openapi/metamodel/metamodel.pure
> +  specificationExtensions: Map<String, List<meta::external::format::openapi::transformation::fromPure::TDSResult>>[0..1];
this has no place in metamodel

2023-10-23 12:38 UTC, finos-admin commented
This PR is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

2023-10-29 12:35 UTC, finos-admin commented
This PR was closed because it has been inactive for 35 days. Please re-open if this PR is still relevant.

2023-10-29 12:36 UTC, closed without merging