Fix number overflow issues with adjust operations on date
finos/legend-engine pull request #2220
Opened 2023-09-04 13:53 UTC by hardikmaheshwari

#### What type of PR is this?
Improvement

#### What does this PR do / why is it needed ?
Fix number overflow issues with adjust operations on date

#### Which issue(s) this PR fixes:

Fixes #

#### Other notes for reviewers:

#### Does this PR introduce a user-facing change?

2023-09-05 19:36 UTC, kevin-m-knight-gs requested changes

2023-09-05 19:36 UTC, kevin-m-knight-gs commented on legend-engine-core/legend-engine-core-executionPlan-execution/legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/PureDate.java
> +        long remDelta = this.day + delta;
```suggestion
        long remDelta = Math.addExact(this.day, delta);
```

2023-09-05 19:36 UTC, kevin-m-knight-gs commented on legend-engine-core/legend-engine-core-executionPlan-execution/legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/PureDate.java
>          this.year += delta;
```suggestion
        long newYear = Math.addExact(this.year, delta);
        if ((newYear > Integer.MAX_VALUE) || (newYear < Integer.MIN_VALUE))
        {
            throw new IllegalStateException("Year incremented beyond supported bounds");
        }
        this.year = (int) newYear;
```

2023-09-05 19:36 UTC, kevin-m-knight-gs commented on legend-engine-core/legend-engine-core-executionPlan-execution/legend-engine-executionPlan-dependencies/src/main/java/org/finos/legend/engine/plan/dependencies/domain/date/PureDate.java
> +    public PureDate addWeeks(long weeks)
We should use Math.multiplyExact(7L, weeks) here to avoid the possibility of overflow.

2023-09-06 14:04 UTC, kevin-m-knight-gs submitted a review, later dismissed

2023-09-08 07:47 UTC, gs-ssh16 approved these changes

2023-09-08 07:48 UTC, merged