Initial PR for the RelationalAI extension
finos/legend-engine pull request #2346
Opened 2023-10-05 00:05 UTC by relationalai-opensource

#### What type of PR is this?

- Improvement

#### What does this PR do / why is it needed ?

This PR adds an extension to transpile PURE queries into [Rel](https://docs.relational.ai/) for execution on [RAI Cloud](https://relational.ai/).

For example, given the PURE class:
```
Class Person {
  firstName: String[1];
  lastName: String[1];
}
```
this extension will transpile the PURE query `Person.all()` into the following corresponding Rel query:
```
def output[:query](x) = Person(x)
def output[:firstName] = Person:firstName[x] for x where output[:query](x)
def output[:lastName] = Person:lastName[x] for x where output[:query](x)
```

2023-10-06 13:00 UTC, rafaelbey requested changes
Overall looks good!  

There are few changes that can impact broadly, like the files under the /dev directory or the inclusion of a new CoreRepository.

I added few comments with a [minor] tag, more as to understand these functions and the rational behind them, and try to see if there is a gap on the existing core functions, since some of these functions could graduate with minor or no changes to core to make them accessible to all pure repos.

2023-10-09 19:14 UTC, relationalai-opensource commented on legend-engine-pure/legend-engine-pure-ide/legend-engine-pure-ide-light/src/main/java/org/finos/legend/engine/ide/LibCodeRepository.java
> +public class LibCodeRepository extends CodeRepository
This file has now been removed.

2023-10-09 19:19 UTC, relationalai-opensource commented on legend-engine-pure-ide-light/dev/scratch/json_showcase.pure
This file has been removed.

2023-10-09 19:19 UTC, relationalai-opensource commented on legend-engine-pure-ide-light/dev/welcome.pure
This file has been removed.

2023-10-09 19:38 UTC, relationalai-opensource commented on legend-engine-xts-relationalai/legend-engine-xt-relationalai-pure/src/main/resources/core_external_query_relationalai/utils/maybe.pure
> +function meta::rel::utils::isSome<T|m>(value: T[m]): Boolean[1] {
This utility function has now been removed (as you rightly say, it can be replaced by `isNotEmpty()`).

2023-10-09 19:44 UTC, relationalai-opensource commented on legend-engine-xts-relationalai/legend-engine-xt-relationalai-pure/src/main/resources/core_external_query_relationalai/utils/maybe.pure
> +function meta::rel::utils::unwrap<T>(value: T[0..1]): T[1] {
These functions have been removed and standard core functions used instead.

2023-10-09 20:27 UTC, relationalai-opensource commented on legend-engine-xts-relationalai/legend-engine-xt-relationalai-pure/src/main/resources/core_external_query_relationalai/utils/maybe.pure
> +  let m = $source.source + ' at ' + $source.line->toString()->toOne() + ':';
This function has been removed.

2023-10-11 20:40 UTC, rafaelbey commented on legend-engine-xts-relationalai/legend-engine-xt-relationalai-pure/pom.xml
> +        <version>4.30.3-SNAPSHOT</version>
That still not correct.  The group id was correct, but the artifact is what needed to change

```xml
<parent>
        <groupId>org.finos.legend.engine</groupId>
        <artifactId>legend-engine-xts-relationalai</artifactId>
        <version>4.30.3-SNAPSHOT</version>
  </parent>
```

2023-10-12 00:38 UTC, rafaelbey approved these changes

2023-10-12 19:11 UTC, relationalai-opensource commented
The CLA has now been signed by all parties. Many thanks!

2023-10-12 21:17 UTC, merged