Repl
finos/legend-engine pull request #2745
Opened 2024-04-02 13:55 UTC by gayathrir11

2024-04-03 06:55 UTC, aziemchawdhary-gs commented on legend-engine-config/legend-engine-repl/legend-engine-repl-relational/pom.xml
> +        <repl.web-application.url>https://registry.npmjs.org/@finos/legend-application-repl-deployment/-/legend-application-repl-deployment-${repl.web-application.version}.tgz</repl.web-application.u
Is it possible to make the initial part of the URL a Maven property? We have two places where we download dependencies from a NPM repository (here and also Pure IDE Light HTTP server pom). 
If we could extract out https//registry.npmjs.org into a central place then that makes it easier to change the URL when building in a corporate enviroment where registry.npmjs.org may be blocked.

2024-04-04 23:01 UTC, rafaelbey approved these changes

2024-04-04 23:06 UTC, rafaelbey requested changes
The build failed on the dependency enforcer

> [INFO] --- maven-dependency-plugin:2.10:analyze-only (dependency-analyze) @ legend-engine-repl-relational ---
Warning:  Used undeclared dependencies found:
Warning:     com.fasterxml.jackson.core:jackson-annotations:jar:2.10.5:compile

2024-04-05 19:14 UTC, pierredebelen approved these changes

2024-04-05 21:12 UTC, merged