add qualified service in dataspace coverage API
finos/legend-engine pull request #3078
Opened 2024-09-09 17:52 UTC by YannanGao-gs

#### What type of PR is this?

#### What does this PR do / why is it needed ?

Improvement

add qualified service in dataspace coverage API

#### Which issue(s) this PR fixes:

Fixes #

#### Other notes for reviewers:

#### Does this PR introduce a user-facing change?

2024-09-09 18:30 UTC, YannanGao-gs commented
contains changes in https://github.com/finos/legend-engine/pull/3071

2024-09-13 13:45 UTC, MauricioUyaguari requested changes

2024-09-13 13:45 UTC, MauricioUyaguari commented on legend-engine-xts-data-space/legend-engine-xt-data-space-generation/src/main/java/org/finos/legend/engine/generation/analytics/DataSpaceAnalyticsHelper.java
> +                //compile
lets remove this comment for now

2024-09-13 13:45 UTC, MauricioUyaguari commented on legend-engine-xts-data-space/legend-engine-xt-data-space-generation/src/main/java/org/finos/legend/engine/generation/analytics/DataSpaceAnalyticsHelper.java
> +                        return false;
is this expected. are we not including all non service executables ?

2024-09-13 13:45 UTC, MauricioUyaguari commented on legend-engine-xts-data-space/legend-engine-xt-data-space-generation/src/main/java/org/finos/legend/engine/generation/analytics/DataSpaceAnalyticsHelper.java
> +                        return true;
if the above is false, then why is this true ?

2024-09-16 20:10 UTC, YannanGao-gs commented
will be closed by https://github.com/finos/legend-engine/pull/3080

2024-09-16 20:10 UTC, closed without merging