Add GCP Workload Identity Federation Using AWS Auth Strategy
finos/legend-engine pull request #589
Opened 2022-03-10 13:28 UTC by abhishoya-gs

Add GCP Workload Identity Federation Using AWS Auth Strategy

2022-03-10 14:35 UTC, epsstan requested changes

2022-03-10 14:35 UTC, epsstan commented on .github/workflows/database-bigquery-integration-test.yml
> +  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
Prefix secrets used in tests with LEGEND_INTEG_TEST

2022-03-10 14:35 UTC, epsstan commented on legend-engine-executionPlan-execution-store-authentication/src/main/java/org/finos/legend/engine/authentication/flows/BigQueryWithGCPWorkloadIdentityFederationUsingAWSFlow.java
> +                .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(Vault.INSTANCE.getValue(awsAccessKeyIdVaultReference),Vault.INSTANCE.getValue(awsSecretAccessKeyVaultR
Minor. Indent VAULT api invocation

2022-03-10 14:35 UTC, epsstan commented on legend-engine-executionPlan-execution-store-authentication/src/test/java/org/finos/legend/engine/authentication/flows/ExternalIntegration_TestBigQueryWithGCPWorkloadIdentityFederationUsingAWSFlow.java
> +    private final Identity identity1 = IdentityFactoryProvider.getInstance().makeIdentityForTesting("identity1");
Replace inmemory vault with env vault 
```
  @BeforeClass
    public static void setupTest() throws IOException
    {
        Vault.INSTANCE.registerImplementation(new EnvironmentVaultImplementation());
    }
```

2022-03-10 14:35 UTC, epsstan commented on legend-engine-executionPlan-execution-store-relational-connection-tests/pom.xml
> +                            <includes>
Make test selection consistent with other database integration tests

2022-03-10 14:35 UTC, epsstan commented on legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_BigQuery.java
>             // fail(String.format("Tests cannot be run. GCP env variable %s has not been set", GOOGLE_APPLICATION_CREDENTIALS));
Remove GCP comments

2022-03-10 14:35 UTC, epsstan commented on legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_BigQuery.java
> +            // fail(String.format("Tests cannot be run. AWS env variable %s has not been set", AWS_ACCESS_KEY_ID));
Put back the comments

2022-03-10 14:35 UTC, epsstan commented on legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_BigQuery.java
> +        Vault.INSTANCE.registerImplementation(inMemoryVault);
In memory vault not needed

2022-03-10 14:35 UTC, epsstan commented on legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_BigQuery.java
> +        assertBigQueryWifUsingAwsFlowIsAvailable(flowProvider);
Minor. Consistent abbreviations. GCP/WIF vs Gcp/Wif

2022-03-10 14:35 UTC, epsstan commented on legend-engine-executionPlan-execution-store-authentication/pom.xml
>              <groupId>com.fasterxml.jackson.core</groupId>
Figure out how to add Simba to main server classpath

2022-04-05 10:31 UTC, abhishoya-gs commented on legend-engine-executionPlan-execution-store-relational-connection-tests/src/test/java/org/finos/legend/engine/plan/execution/stores/relational/connection/test/ExternalIntegration_TestConnectionAcquisitionWithFlowProvider_BigQuery.java
> +//            fail(String.format("Tests cannot be run. GCP env variable %s has not been set", GOOGLE_APPLICATION_CREDENTIALS));
Done

2022-04-05 10:39 UTC, abhishoya-gs commented on .github/workflows/database-bigquery-integration-test.yml
> +  AWS_ACCESS_KEY_ID: ${{ secrets.LEGEND_INTEG_TEST_AWS_ACCESS_KEY_ID }}
Right, including them in steps now

2022-04-05 10:40 UTC, abhishoya-gs commented on legend-engine-language-pure-store-relational/src/main/java/org/finos/legend/engine/language/pure/grammar/from/authentication/AuthenticationStrategyParseTreeWalker.java
> +
Added [here](https://github.com/finos/legend-engine/pull/589/commits/fb2c4aa1ba052e59980ff5e8174f723f2cefcbd1#diff-a428f06079ed306ac6336a7e6a64b2a7c33a61c068e8983b090f415d9f018901)

2022-04-05 18:09 UTC, abhishoya-gs commented on legend-engine-executionPlan-execution-store-authentication/src/main/java/org/finos/legend/engine/authentication/LegendDefaultDatabaseAuthenticationFlowProviderConfiguration.java
> +    public AWSConfig awsConfig;
Refactored it [here](https://github.com/finos/legend-engine/pull/589/commits/65bc7a3008c1d4ee308ec60aa945122d7c40985a)

2022-04-06 00:01 UTC, epsstan approved these changes

2022-04-06 06:57 UTC, abhishoya-gs commented on legend-engine-executionPlan-execution-store-authentication/src/test/java/org/finos/legend/engine/authentication/flows/ExternalIntegration_TestBigQueryWithGCPWorkloadIdentityFederationFlow.java
> +                "412074507462",
Done

2022-04-06 06:57 UTC, abhishoya-gs commented on legend-engine-executionPlan-execution-store-authentication/src/test/java/org/finos/legend/engine/authentication/flows/ExternalIntegration_TestBigQueryWithGCPWorkloadIdentityFederationFlow.java
> +                "564704738649",
Done

2022-04-06 06:57 UTC, abhishoya-gs commented on legend-engine-executionPlan-execution-store-authentication/src/test/java/org/finos/legend/engine/authentication/TestDefaultSupportedFlows.java
> +                { DatabaseType.BigQuery, BigQueryDatasourceSpecification.class, GCPWorkloadIdentityFederationAuthenticationStrategy.class}
Done

2022-04-06 06:58 UTC, abhishoya-gs commented on docs/bigquery/bigquery-connector.md
> +Legend can connect to BigQuery using Workload Identity Federation. This means that BigQuery JDBC driver will require any valid Service Account Access Token obtained using configured authentication fl
Okay, changed

2022-05-20 13:03 UTC, merged