Modify parameters for BigQuery DataSource Spec
finos/legend-engine pull request #618
Opened 2022-03-28 06:38 UTC by abhishoya-gs

Adding proxy parameters (host and port) in BigQuery DataSource Spec 
Move OAuthType parameter's declaration to Auth strategy

2022-04-04 12:34 UTC, epsstan requested changes

2022-04-04 12:34 UTC, epsstan commented on legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/datasource/DataSourceSpecificationParserGrammar.g4
> +                                                        | dbProxyHost
Please add grammar/parser roundtrip tests.

2022-04-05 10:03 UTC, abhishoya-gs commented on legend-engine-language-pure-store-relational/src/main/antlr4/org/finos/legend/engine/language/pure/grammar/from/antlr4/connection/datasource/DataSourceSpecificationParserGrammar.g4
> +                                                        | dbProxyHost
Added [here](https://github.com/finos/legend-engine/pull/618/commits/3b4e0fe26e3ef10bcfe832eb00e0873e3b6e91f8)

2022-04-07 13:33 UTC, epsstan approved these changes
Approved

2022-04-07 18:29 UTC, merged